/**
 * DEVELOPMENT WEBPACK CONFIGURATION
 */
import CircularDependencyPlugin from 'circular-dependency-plugin';
import HtmlWebpackPlugin from 'html-webpack-plugin';
import MiniCssExtractPlugin from 'mini-css-extract-plugin';
import path from 'path';
import ejsLoader from 'template-ejs-loader';
import webpack from 'webpack';

import { publicPath } from '../server/config.mjs';
import templatePath from '../server/utils/templatePath.mjs';
import clientConfig from './clientConfig/index.mjs';
import webpackBaseBabel from './webpack.base.babel.mjs';

export default webpackBaseBabel({
  mode: 'development',

  // Add hot reloading in development
  entry: [
    'webpack-hot-middleware/client?reload=true',
    path.join(process.cwd(), 'app/app.mjs'), // Start with js/app.mjs
  ],

  // Don't use hashes in dev mode for better performance
  output: {
    filename: '[name].js',
    chunkFilename: '[name].chunk.js',
    publicPath,
    clean: true,
  },

  optimization: {
    splitChunks: {
      chunks: 'all',
    },
  },

  // Add development plugins
  plugins: [
    new webpack.HotModuleReplacementPlugin(), // Tell webpack we want hot reloading

    new MiniCssExtractPlugin({
      filename: '[name].css',
      chunkFilename: '[id].css',
    }),

    new HtmlWebpackPlugin({
      inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
      template: ejsLoader.htmlWebpackPluginTemplateCustomizer({
        templatePath,
        htmlLoaderOption: {},
        templateEjsLoaderOption: {
          data: {
            ...clientConfig.default.templateData,
            IS_GTM: true,
            PUBLIC_PATH: publicPath,
            APP: process.env.APP,
          },
        },
      }),
    }),

    new CircularDependencyPlugin({
      exclude: /a\.js|node_modules/, // exclude node_modules
      failOnError: false, // show a warning when there is a circular dependency
    }),
  ],

  // Emit a source map for easier debugging
  // See https://webpack.js.org/configuration/devtool/#devtool
  devtool: 'eval-source-map',

  performance: {
    hints: false,
  },
});
